[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/Ibneilyas124/my-esp32-project
    https://github.com/Ibneilyas124/my-esp32-project
